language: fr

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
  case_sensitive: false
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 200
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 200
assistant_id: 20250325-100425-alternating-appraisal
