FROM python:3.8-slim

WORKDIR /app

# Copier les fichiers de dépendances
COPY requirements.txt .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier le bot Discord
COPY bot/ /app/bot/

# Démarrer le bot Discord
CMD python bot/main.py
